# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'flights.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rflights.proto\x12\x06travel\"(\n\x07\x41irport\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x11\x12\x0f\n\x07\x61irport\x18\x02 \x01(\t\"\x87\x01\n\rItineraryData\x12\x19\n\x11\x64\x65parture_airport\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65parture_date\x18\x02 \x01(\t\x12\x17\n\x0f\x61rrival_airport\x18\x03 \x01(\t\x12\x13\n\x0b\x66light_code\x18\x05 \x01(\t\x12\x15\n\rflight_number\x18\x06 \x01(\t\"\xc6\x01\n\nFlightData\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12(\n\titin_data\x18\x04 \x01(\x0b\x32\x15.travel.ItineraryData\x12\x16\n\tmax_stops\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x10\n\x08\x61irlines\x18\x06 \x03(\t\x12$\n\x0b\x66rom_flight\x18\r \x03(\x0b\x32\x0f.travel.Airport\x12\"\n\tto_flight\x18\x0e \x03(\x0b\x32\x0f.travel.AirportB\x0c\n\n_max_stops\"y\n\x0e\x42ookingRequest\x12#\n\x07\x66lights\x18\x03 \x03(\x0b\x32\x12.travel.FlightData\x12\x17\n\x0fpassengers_flag\x18\x08 \x01(\x11\x12\x11\n\tseat_flag\x18\t \x01(\x11\x12\x16\n\x0einfo_trip_flag\x18\x13 \x01(\x11*E\n\x04Trip\x12\x10\n\x0cUNKNOWN_TRIP\x10\x00\x12\x0e\n\nROUND_TRIP\x10\x01\x12\x0b\n\x07ONE_WAY\x10\x02\x12\x0e\n\nMULTI_CITY\x10\x03*_\n\tPassenger\x12\x15\n\x11UNKNOWN_PASSENGER\x10\x00\x12\t\n\x05\x41\x44ULT\x10\x01\x12\t\n\x05\x43HILD\x10\x02\x12\x12\n\x0eINFANT_IN_SEAT\x10\x03\x12\x11\n\rINFANT_ON_LAP\x10\x04*S\n\x04Seat\x12\x10\n\x0cUNKNOWN_SEAT\x10\x00\x12\x0b\n\x07\x45\x43ONOMY\x10\x01\x12\x13\n\x0fPREMIUM_ECONOMY\x10\x02\x12\x0c\n\x08\x42USINESS\x10\x03\x12\t\n\x05\x46IRST\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flights_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIP']._serialized_start=529
  _globals['_TRIP']._serialized_end=598
  _globals['_PASSENGER']._serialized_start=600
  _globals['_PASSENGER']._serialized_end=695
  _globals['_SEAT']._serialized_start=697
  _globals['_SEAT']._serialized_end=780
  _globals['_AIRPORT']._serialized_start=25
  _globals['_AIRPORT']._serialized_end=65
  _globals['_ITINERARYDATA']._serialized_start=68
  _globals['_ITINERARYDATA']._serialized_end=203
  _globals['_FLIGHTDATA']._serialized_start=206
  _globals['_FLIGHTDATA']._serialized_end=404
  _globals['_BOOKINGREQUEST']._serialized_start=406
  _globals['_BOOKINGREQUEST']._serialized_end=527
# @@protoc_insertion_point(module_scope)
